routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',[
    'as'=>'admin.dashboard',
    'uses'=>function(){
    return view('admin.dashboard');
    }
]);
Route::resource('role','RoleController');
Route::resource('assignrole','AssignRoleController');
Route::resource('register','RegisterController');
Route::resource('login','loginController');

//Route::get('/pass/create','RegisterController@password')->name('createPass');
//Route::post('/login','RegisterController@submitPassword')->name('submitPass');
Route::get('/verify/{varification_token}','VerifyController@verify')->name('verify');

app/Http/Controllers/RegisterController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;


class RegisterController extends Controller
{

    public function index()
    {
        $users = User::all();
        return view('admin.register.usersProfile', compact('users'));
    }


    public function create()

    {
        $roles = Role::all();
        return view('admin.register.registration', compact('roles'));
    }


    public function store(Request $request)
    {    /*validation*/
        $rules = [
            'name' => 'required',
            'mobile' => 'required|unique:users',
            'email' => 'required|unique:users|email',
            'address' => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }

        /*Insert into db*/
        $user = User::create([
            'full_name' => $request['name'],
            'mobile' => $request['mobile'],
            'email' => $request['email'],
            'address' => $request['address'],
            'varification_token' => md5(str_random(25)),

        ]);

        foreach ($request->input('role') as $key => $value) {
            $user->attachRole($value);
        }


        /* Redirect*/

        $user->sendVerificationEmail();
        return redirect()->route('register.index')->with('success', 'User created successfully and verification mail has been sent');
    }


    public function show($id)
    {

    }


    public function edit($id)
    {
        /*get info by user id */
        $users = User::find($id);
        $roles = Role::get();
        $role_user = DB::table("role_user")
            ->where("role_user.user_id", $id)
            ->pluck('role_user.role_id', 'role_user.role_id')->toArray();
        return view('admin.register.editUser', compact(['users', 'roles', 'role_user']));
    }


    public function update(Request $request, $id)
    {
        /*validation*/
        $rules = [
            'name' => 'required',
            'mobile' => 'required',
            'email' => 'required',
            'address' => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator);
        }
        //update user info
        $user = User::find($id);
        $user->full_name = $request->name;
        $user->mobile = $request->mobile;
        $user->email = $request->email;
        $user->address = $request->address;
        $user->save();
        DB::table('role_user')->where('user_id', $id)->delete();
        foreach ($request->input('role') as $key => $value) {
            $user->attachRole($value);
        }
        /*Redirect*/
        return redirect()->route('register.index')
            ->with('success', 'User Updated successfully');
    }


    public function destroy($id)
    {
        DB::table('users')->where('id', $id)->delete();
        return redirect()->route('register.index')
            ->with('success', 'User Deleted successfully');
    }

}

resources/views/Admin/register/editUser.blade.php
@extends('layouts.dashboard')
@section('content')
    <a href="{{route('register.index')}}" class="btn btn-primary"> Back</a>
    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger">
                <p>{{$error}}</p>
            </div>
        @endforeach
    @endif
    <h3>Edit roles</h3>

    <form action="{{route('register.update',$users->id)}}" method="post">
        {{csrf_field()}}
        {{method_field('PATCH')}}
        <div class="form-group">
            <label for="name">Full Name</label>
            <input type="text" value="{{$users->full_name}}" class="form-control" id="name" name="name">
        </div>
        <div class="form-group">
            <label for="mobile">Mobile No</label>
            <input type="text" class="form-control" id="mobile" name="mobile" value="{{$users->mobile}}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" id="email" name="email" value="{{$users->email}}">
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" name="address" value="{{$users->address}}">
        </div>
        <div class="form-group">
            <label for="roll">Roles</label> <br>
            @foreach($roles as $role)
                <input type="checkbox" {{in_array($role->id,$role_user)?"checked":""}}  id="roll" name="role[]" value="{{$role->id}}" > {{$role->name}} <br>
            @endforeach

        <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>
@endsection

resources/views/Admin/register/editregistration.blade.php
@extends('layouts.dashboard')
@section('content')
    <h1 class="text-center">USER REGISTRATION</h1>
    <form action="{{route('register.store')}}" method="post">
        {{csrf_field()}}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Users Name">
        </div>
        <div class="form-group">
            <label for="mobile">Mobile No</label>
            <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Users Mobile No">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" id="email" name="email" placeholder="Users Email">
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" name="address" placeholder="Users Address">
        </div>
        <div class="form-group">
            <label for="image">Image</label>
            <input type="file" class="form-control" id="image" name="image" placeholder="Users Image">
        </div>

        <button type="submit" class="btn btn-primary">Register</button>
    </form>
@endsection

resources/views/Admin/register/password.blade.php
@extends('layouts.login')
@section('upper-content')
    <h3>
        Create your pass
    </h3>
    @endsection

@section('middle-content')
    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <p>{{$error}}</p>
            </div>
        @endforeach
    @endif
    <form action="{{route('login.store')}}" method="post">
        {{csrf_field()}}
        <div class="form-group">
        <label for="pass">Password</label>
        <input type="text" name="pass" id="pass"  class="form-control">
        </div>
        <div class="form-group">
        <label for="rpass">Retype Password</label>
        <input type="text"  name="retypepass" id="rpass"   class="form-control">
        </div>
        <br>
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
    @endsection

resources/views/Admin/register/registration.blade.php
@extends('layouts.dashboard')
@section('content')
    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <p>{{$error}}</p>
            </div>
        @endforeach
    @endif
    @if(session()->has('message'))
        <div class="alert alert-{{session('type')}}">
            {{session('message')}}
        </div>
        @endif
  <h1 class="text-center">USER REGISTRATION</h1>
  <form action="{{route('register.store')}}" method="post">
  {{csrf_field()}}
  <div class="form-group">
      <label for="name">Full Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Users Full Name">
  </div>
  <div class="form-group">
      <label for="mobile">Mobile No</label>
      <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Users Mobile No">
  </div>
  <div class="form-group">
      <label for="email">Email</label>
      <input type="text" class="form-control" id="email" name="email" placeholder="Users Email">
  </div>
  <div class="form-group">
      <label for="address">Address</label>
      <input type="text" class="form-control" id="address" name="address" placeholder="Users Address">
  </div>
  <div class="form-group">
      <label for="roll">Roles</label> <br>
      @foreach($roles as $role)
              <input type="checkbox" id="roll" name="role[]" value="{{$role->id}}" > {{$role->name}} <br>
      @endforeach

  </div>
  <button type="submit" class="btn btn-primary">Register</button>
  </form>
@endsection

resources/views/Admin/register/usersProfile.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container">
        <h1 class="text-center">Users Info</h1>
        <br>
        @if(session('success'))
            <div class="alert alert-dismissible alert-success">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <p>{{session('success')}}</p>
            </div>
        @endif

        <table class="table table-dark table-hover">
            <tr>
                <th>Full Name</th>
                <th>Mobile</th>
                <th>Email</th>
                <th>Address</th>
                <th>Action</th>
            </tr>
            @forelse($users as $user)
                <tr>
                    <td>{{$user->full_name}}</td>
                    <td>{{$user->mobile}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->address}}</td>
                    <td>
                        <a class="btn btn-raised btn-primary btn-sm" href="{{ route('register.edit',$user->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        <form action="{{route('register.destroy',$user->id)}}" id="delete-form-{{ $user->id }}" method="post"  style="display: none;">
                            {{ csrf_field() }}
                            {{ method_field('delete') }}
                        </form>
                        <button onclick="if(confirm('Are you Sure, You went to delete this?')){
                                event.preventDefault();
                                document.getElementById('delete-form-{{ $user->id }}').submit();
                                }else{
                                event.preventDefault();
                                }" class="btn btn-raised btn-danger btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                    </td>
                </tr>
            @empty
                <tr>
                    <td>No Register User</td>
                </tr>
            @endforelse


        </table>




    </div>





@endsection