routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/',[
    'as'=>'admin.dashboard',
    'uses'=>function(){
    return view('admin.dashboard');
    }
]);
Route::resource('role','RoleController');
Route::resource('assignrole','AssignRoleController');
Route::resource('register','RegisterController');
Route::resource('login','loginController');

//Route::get('/pass/create','RegisterController@password')->name('createPass');
//Route::post('/login','RegisterController@submitPassword')->name('submitPass');
Route::get('/verify/{varification_token}','VerifyController@verify')->name('verify');

app/Role.php
<?php namespace App;

use Zizaco\Entrust\EntrustRole;

class Role extends EntrustRole
{
    protected $fillable=['name','display_name','description'];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles=Role::all();
        return view('admin.role.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   $permissions= Permission::all();
        return view('admin.role.create',compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'name'=>'required',
           'display_name'=>'required',
           'description'=>'required',
           'permission'=>'required',
        ]);

        $role=Role::create($request->except(['permission','_token']));
        foreach ($request->input('permission') as $key => $value) {
            $role->attachPermission($value);
        }
        return redirect()->route('role.index')
            ->with('success','Role created successfully');
    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role=Role::find($id);
        $permissions=Permission::get();
        $role_permission = DB::table("permission_role")
            ->where("permission_role.role_id",$id)
            ->pluck('permission_role.permission_id','permission_role.permission_id')->toArray();
//        dd($role);
//        dd($role_permission);
        return view('admin.role.edit',compact(['role','role_permission','permissions']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'display_name'=>'required',
            'description'=>'required',
            'permission'=>'required',
        ]);

        $role=Role::find($id);
        $role->name=$request->name;
        $role->display_name=$request->display_name;
        $role->description=$request->description;
        $role->save();
        DB::table('permission_role')->where('role_id',$id)->delete();


        foreach ($request->input('permission') as $key => $value) {
            $role->attachPermission($value);
        }
        return redirect()->route('role.index')
            ->with('success','Role Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('roles')->where('id',$id)->delete();
        return redirect()->route('role.index')
        ->with('success','Role Deleted successfully');
    }

}

resources/views/Admin/role/assignrole.blade.php
@extends('layouts.dashboard')
@section('content')

    <h3 class="text-center">Assign roles</h3>
    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <p>{{$error}}</p>
            </div>
        @endforeach
    @endif

    <form action="{{route('assignrole.store')}}" method="post">
        {{csrf_field()}}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" placeholder="Write a name">
        </div>
        <div class="form-group">
            <label for="roles">Role</label>
            <select name="roles" id="roles" class="form-control">
            <option disabled selected value >Select Role</option>
                @foreach($roles as $role)
            <option value="{{$role->name}}">{{$role->name}}</option>
            @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>


@endsection

resources/views/Admin/role/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <a href="{{route('role.index')}}" class="btn btn-primary"> Back</a>
    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <p>{{$error}}</p>
            </div>
        @endforeach
    @endif
    <h3>Create roles</h3>

    <form action="{{route('role.store')}}" method="post">
        {{csrf_field()}}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" placeholder="Name of role">
        </div>
        <div class="form-group">
            <label for="display_name">Display Name</label>
            <input type="text" class="form-control" name="display_name" placeholder="Display Name">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" name="description" placeholder="Description of role">
        </div>
        <div class="form-group">
            <label for="permission">Permission</label> <br>
            @foreach($permissions as $permission)
                <input type="checkbox" name="permission[]" value="{{$permission->id}}"> {{$permission->name}} <br>
            @endforeach
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/Admin/role/edit.blade.php
@extends('layouts.dashboard')
@section('content')
    <a href="{{route('role.index')}}" class="btn btn-primary"> Back</a>
    @if($errors->any())
        @foreach($errors->all() as $error)
            <div class="alert alert-danger">
                <p>{{$error}}</p>
            </div>
        @endforeach
    @endif
    <h3>Edit roles</h3>

    <form action="{{route('role.update',$role->id)}}" method="post">
        {{csrf_field()}}
        {{method_field('PATCH')}}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" value="{{$role->name}}" class="form-control" name="name" placeholder="Name of role">
        </div>
        <div class="form-group">
            <label for="display_name">Display Name</label>
            <input type="text" value="{{$role->display_name}}" class="form-control" name="display_name" placeholder="Display Name">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" value="{{$role->description}}"    class="form-control" name="description" placeholder="Description of role">
        </div>
        <div class="form-group">
            <label for="permission">Permission</label> <br>
            @foreach($permissions as $permission)
                <input type="checkbox" {{in_array($permission->id,$role_permission)?"checked":""}} name="permission[]" value="{{$permission->id}}" > {{$permission->name}} <br>
            @endforeach
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/Admin/role/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container">
    <div class="create" style="margin-bottom: 50px">
    <a class="btn btn-success " href="{{route('role.create')}}">Create Role</a>
    </div>
    @if(session('success'))
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <p>{{session('success')}}</p>
        </div>
    @endif

    <table class="table table-dark table-hover">
        <tr>
            <th>Name</th>
            <th>Display Name</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        @forelse($roles as $role)
            <tr >
                <td>{{$role->name}}</td>
                <td>{{$role->display_name}}</td>
                <td>{{$role->description}}</td>
                <td>
                    <a class="btn btn-raised btn-primary btn-sm" href="{{ route('role.edit',$role->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <form action="{{route('role.destroy',$role->id)}}" id="delete-form-{{ $role->id }}" method="post"  style="display: none;">
                        {{ csrf_field() }}
                        {{ method_field('delete') }}


                    </form>
                    <button onclick="if(confirm('Are you Sure, You went to delete this?')){
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $role->id }}').submit();
                            }else{
                            event.preventDefault();
                            }" class="btn btn-raised btn-danger btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                </td>
            </tr>
            @empty
        <tr>
            <td>No Roles</td>
        </tr>
            @endforelse


    </table>




</div>





    @endsection